version: 2.1

jobs:
  buid:
     docker:
          - image: cimg/python:3.11

          steps:
              - checkout
              - run: python main.py

test:
  docker:
    - imahge: cimg/python:3.11
  steps:
    - checkout
    - run: python test.py

deploy:
  docker:
    - image: cimg/python:3.11

  steps:
    - run: echo "Deploying to practical done"


workflows:
  build_and_test:
      jobs:
        - build
        - test:
            reqiures:
              -build
        - deploy:
            requires:
              - test
            filters:
              - branches:
                  only: main
