version: 2.1

jobs:
  buid:
     docker:
          - image: cimg/python:3.11

          steps:
              - checkout
              - run: python main.py


workflows:
  build_and_test:
      jobs:
        - build
